export default {
  "\\R": "\\mathbb{R}",
  "\\de": "\\mathrm{d}#1",
  "\\vmx": "{\\bf{x}}",
  "\\vmw": "{\\bf{w}}",
  "\\vmX": "{\\bf{X}}",
  "\\nsamp": "k",
  "\\nfeat": "p",
  "\\nest": "T",
  "\\npart": "J",
  "\\xhat": "\\hat{\\vmx}",
  "\\yhat": "\\hat{y}",
  "\\loss": "\\mathcal{L}",
  "\\defeq": ":=",
  "\\eqdef": "=:",
  "\\card": "|#1|",
  "\\abs": "\\left|#1\\right|",
  "\\opt": "{#1^\\ast}",
  "\\argmin": "\\mathop{\\operatorname{argmin}}\\limits",
  "\\E": "\\mathbb{E}",
  "\\P": "\\mathbb{P}",
  "\\comp": "\\bar",
  "\\parens": "\\left(#1\\right)",
  "\\braces": "\\left\\{#1\\right\\}",
  "\\brackets": "\\left[#1]\\right",
  "\\event": "\\mathcal{E}",
  "\\ind": "\\chi_{{#1}}",
  "\\inner": "\\left\\langle#1,#2\\right\\rangle",
  "\\set": "\\{#1\\}",
  "\\setpred": "\\{#1 \\mid #2 \\}", // Set with predicate
  "\\family": "\\mathcal{F}",
  "\\function": "#1\\colon#2\\to#3",
  "\\bigO": "\\mathcal{O}",
  "\\Trainset": "\\mathcal{D}",
  "\\norm": "\\|#1\\|"
};
